apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: lab2-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lab2-app
    spec:
      containers:
        - image: lab2:latest
          imagePullPolicy: Never
          name: lab2
          ports:
            - containerPort: 8080
      hostAliases:
        - ip: "192.168.99.101"
          hostnames:
            - postgres.local
