apiVersion: v1
kind: Service
metadata:
  name: lab2-service
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: lab2-app